app/models/ModelVideo.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class Video(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    input_video_path = db.Column(db.String(200), nullable=False)
    output_video_path = db.Column(db.String(200))
    upload_time = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    process_time = db.Column(db.DateTime)

    def __init__(self, input_video_path):
        self.input_video_path = input_video_path

app/__init__.py
from flask import Flask, render_template
from flask_migrate import Migrate
from config import config
from app.models.ModelVideo import db

def create_app(config_class):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate = Migrate(app, db)

    with app.app_context():
        from app.routes.Video import video_bp
        app.register_blueprint(video_bp, url_prefix='/api/video')
        
        # Ruta principal
        @app.route('/')
        def index():
            return render_template('index.html')
        
        return app

app/routes/Video.py
from flask import Blueprint, request, jsonify, send_from_directory, current_app, render_template, redirect, url_for
from werkzeug.utils import secure_filename
from video import process_video  # Importar la función de procesamiento de video
from app.models.ModelVideo import db, Video  # Importar solo Video
from datetime import datetime
import os

video_bp = Blueprint('video_bp', __name__)

@video_bp.route('/upload', methods=['GET', 'POST'])
def upload_video():
    if request.method == 'POST':
        if 'file' not in request.files:
            return jsonify({'error': 'No file part'}), 400

        file = request.files['file']
        if file.filename == '':
            return jsonify({'error': 'No selected file'}), 400

        filename = secure_filename(file.filename)
        filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)

        # Crear una entrada en la base de datos para el video subido
        video = Video(input_video_path=filepath)
        db.session.add(video)
        db.session.commit()

        # Process the video
        output_filename_mp4, output_filename_webm = process_video(filepath, filename, current_app.config['MODEL_PATH'], current_app.config['OUTPUT_FOLDER'])
        output_filepath_mp4 = os.path.join(current_app.config['OUTPUT_FOLDER'], output_filename_mp4)
        output_filepath_webm = os.path.join(current_app.config['OUTPUT_FOLDER'], output_filename_webm)

        # Actualizar la entrada en la base de datos con el video procesado
        video.output_video_path = output_filepath_mp4
        video.process_time = datetime.utcnow()
        db.session.commit()

        return render_template('download.html', original_filename=filename, processed_filename_webm=output_filename_webm, processed_filename_mp4=output_filename_mp4)

    return render_template('upload.html')

@video_bp.route('/download', methods=['GET'])
def download_video_page():
    original_filename = request.args.get('original_filename')
    processed_filename = request.args.get('processed_filename')
    return render_template('download.html', original_filename=original_filename, processed_filename=processed_filename)

@video_bp.route('/download/video/<filename>', methods=['GET'])
def download_video(filename):
    return send_from_directory(directory=current_app.config['OUTPUT_FOLDER'], filename=filename, as_attachment=True)

app/templates/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Remove Video Background</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-900 text-white min-h-screen flex flex-col">
    <header class="bg-gray-800 py-4">
        <div class="container mx-auto flex justify-between items-center">
            <div class="logo">
                <a href="/" class="text-white px-4 font-sans text-xl font-bold">Remove Video Background</a>
            </div>            
        </div>
    </header>

    <main class="flex-grow flex flex-col items-center justify-center py-12">
        <section class="text-center mb-12">
            <h1 class="text-4xl font-bold mb-4">Remove Video Background</h1>
            <p class="text-lg mb-8">Elimina los fondos de tus videos!</p>
            <form action="{{ url_for('video_bp.upload_video') }}" method="post" enctype="multipart/form-data" class="space-y-4">
                <label for="upload" class="cursor-pointer bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded inline-block">
                    Upload Clip
                    <input type="file" name="file" class="hidden" id="upload" required>
                </label>
                <button type="submit" class="bg-green-500 hover:bg-green-700 text-white py-2 px-4 rounded">Process</button>
            </form>
            <div class="text-gray-400 mt-4">Ingresa tu archivo en formato .mp4</div>
        </section>

        <section class="flex justify-center space-x-8 mt-12">
            <div class="text-center">
                <h2 class="text-2xl font-bold mb-4">Original Video</h2>
                <div class="relative bg-gray-800 p-4 rounded-lg shadow-lg inline-block">
                    <video id="originalVideo" class="mx-auto mb-4 rounded shadow-lg" controls>
                        <source src="{{ url_for('static', filename='videos/inputs/' + original_filename) }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
            </div>
            <div class="text-center">
                <h2 class="text-2xl font-bold mb-4">Processed Video</h2>
                <div class="relative bg-gray-800 p-4 rounded-lg shadow-lg inline-block">
                    <video id="processedVideo" class="mx-auto mb-4 rounded shadow-lg" controls>
                        <source src="{{ url_for('static', filename='videos/outputs/' + processed_filename_webm) }}" type="video/webm">
                        Your browser does not support the video tag.
                    </video>
                    <div class="flex justify-center mt-4">
                        <a href="{{ url_for('static', filename='videos/outputs/' + processed_filename_mp4) }}" class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded" download>Download</a>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <footer class="bg-gray-800 py-4">
        <div class="container mx-auto text-center text-gray-400">
            &copy; 2024 IA y ML.
        </div>
    </footer>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Remove Video Background</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-900 text-white">
    <header class="bg-gray-800 py-4">
        <div class="container mx-auto flex justify-between items-center">
            <div class="logo">
                <a href="/" class="text-white px-4 font-sans text-xl font-bold">Remove Video Background</a>
            </div>            
        </div>
    </header>
    <main class="flex flex-col items-center min-h-screen py-20">
        <section class="text-center">
            <div class="mb-4">
                <img src="{{ url_for('static', filename='images/remove.png') }}" alt="Remove Background Image" class="w-40 h-40 object-cover mx-auto rounded-full shadow-md">
            </div>
            <h1 class="text-4xl font-bold mb-4">Remove Video Background</h1>
            <p class="text-lg mb-8">Elimina los fondos de tus videos!</p>
            <div class="relative">
                <div class="absolute top-0 left-0 w-full h-full flex flex-col items-center justify-center">
                    <form action="{{ url_for('video_bp.upload_video') }}" method="post" enctype="multipart/form-data" class="space-y-4">
                        <div class="mt-12">
                            <label for="upload" class="cursor-pointer bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded mr-4">
                                Upload Clip
                                <input type="file" name="file" class="hidden" id="upload" required>
                            </label>          
                            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded">Process</button>                  
                        </div>
                    </form>         
                    <div class="text-gray-400 mt-4">Ingresa tu archivo en formato .mp4</div>
                </div>
            </div>
        </section>
    </main>

    <footer class="bg-gray-800 py-4">
        <div class="container mx-auto text-center text-gray-400">
            &copy; 2024 IA y ML.
        </div>
    </footer>
</body>
</html>